name: 'Deployment'

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout Source
              uses: actions/checkout@v3
            - name: Install Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install dependencies
              run: npm install
            - name: Deploy to azure App
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'node-ci-cd'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D58002FCEF6344D8887B23B98789DEAC }}
                package: .


